services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    command: symfony server:start --no-tls
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - .:/app

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: EC
      POSTGRES_USER: EC
      POSTGRES_PASSWORD: EC

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - database