controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

book_read:
    path: /book/read
    controller: App\Controller\BookController::saveBookRead
    methods: POST
